require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AreeTerritorialiController do

  # This should return the minimal set of attributes required to create a valid
  # AreaTerritoriale. As you add validations to AreaTerritoriale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AreeTerritorialiController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aree_territoriali as @aree_territoriali" do
      area_territoriale = AreaTerritoriale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aree_territoriali).should eq([area_territoriale])
    end
  end

  describe "GET show" do
    it "assigns the requested area_territoriale as @area_territoriale" do
      area_territoriale = AreaTerritoriale.create! valid_attributes
      get :show, {:id => area_territoriale.to_param}, valid_session
      assigns(:area_territoriale).should eq(area_territoriale)
    end
  end

  describe "GET new" do
    it "assigns a new area_territoriale as @area_territoriale" do
      get :new, {}, valid_session
      assigns(:area_territoriale).should be_a_new(AreaTerritoriale)
    end
  end

  describe "GET edit" do
    it "assigns the requested area_territoriale as @area_territoriale" do
      area_territoriale = AreaTerritoriale.create! valid_attributes
      get :edit, {:id => area_territoriale.to_param}, valid_session
      assigns(:area_territoriale).should eq(area_territoriale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AreaTerritoriale" do
        expect {
          post :create, {:area_territoriale => valid_attributes}, valid_session
        }.to change(AreaTerritoriale, :count).by(1)
      end

      it "assigns a newly created area_territoriale as @area_territoriale" do
        post :create, {:area_territoriale => valid_attributes}, valid_session
        assigns(:area_territoriale).should be_a(AreaTerritoriale)
        assigns(:area_territoriale).should be_persisted
      end

      it "redirects to the created area_territoriale" do
        post :create, {:area_territoriale => valid_attributes}, valid_session
        response.should redirect_to(AreaTerritoriale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved area_territoriale as @area_territoriale" do
        # Trigger the behavior that occurs when invalid params are submitted
        AreaTerritoriale.any_instance.stub(:save).and_return(false)
        post :create, {:area_territoriale => { "nome" => "invalid value" }}, valid_session
        assigns(:area_territoriale).should be_a_new(AreaTerritoriale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AreaTerritoriale.any_instance.stub(:save).and_return(false)
        post :create, {:area_territoriale => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested area_territoriale" do
        area_territoriale = AreaTerritoriale.create! valid_attributes
        # Assuming there are no other aree_territoriali in the database, this
        # specifies that the AreaTerritoriale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AreaTerritoriale.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => area_territoriale.to_param, :area_territoriale => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested area_territoriale as @area_territoriale" do
        area_territoriale = AreaTerritoriale.create! valid_attributes
        put :update, {:id => area_territoriale.to_param, :area_territoriale => valid_attributes}, valid_session
        assigns(:area_territoriale).should eq(area_territoriale)
      end

      it "redirects to the area_territoriale" do
        area_territoriale = AreaTerritoriale.create! valid_attributes
        put :update, {:id => area_territoriale.to_param, :area_territoriale => valid_attributes}, valid_session
        response.should redirect_to(area_territoriale)
      end
    end

    describe "with invalid params" do
      it "assigns the area_territoriale as @area_territoriale" do
        area_territoriale = AreaTerritoriale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AreaTerritoriale.any_instance.stub(:save).and_return(false)
        put :update, {:id => area_territoriale.to_param, :area_territoriale => { "nome" => "invalid value" }}, valid_session
        assigns(:area_territoriale).should eq(area_territoriale)
      end

      it "re-renders the 'edit' template" do
        area_territoriale = AreaTerritoriale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AreaTerritoriale.any_instance.stub(:save).and_return(false)
        put :update, {:id => area_territoriale.to_param, :area_territoriale => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested area_territoriale" do
      area_territoriale = AreaTerritoriale.create! valid_attributes
      expect {
        delete :destroy, {:id => area_territoriale.to_param}, valid_session
      }.to change(AreaTerritoriale, :count).by(-1)
    end

    it "redirects to the aree_territoriali list" do
      area_territoriale = AreaTerritoriale.create! valid_attributes
      delete :destroy, {:id => area_territoriale.to_param}, valid_session
      response.should redirect_to(aree_territoriali_url)
    end
  end

end
