require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BancheController do

  # This should return the minimal set of attributes required to create a valid
  # Banca. As you add validations to Banca, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BancheController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all banche as @banche" do
      banca = Banca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:banche).should eq([banca])
    end
  end

  describe "GET show" do
    it "assigns the requested banca as @banca" do
      banca = Banca.create! valid_attributes
      get :show, {:id => banca.to_param}, valid_session
      assigns(:banca).should eq(banca)
    end
  end

  describe "GET new" do
    it "assigns a new banca as @banca" do
      get :new, {}, valid_session
      assigns(:banca).should be_a_new(Banca)
    end
  end

  describe "GET edit" do
    it "assigns the requested banca as @banca" do
      banca = Banca.create! valid_attributes
      get :edit, {:id => banca.to_param}, valid_session
      assigns(:banca).should eq(banca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Banca" do
        expect {
          post :create, {:banca => valid_attributes}, valid_session
        }.to change(Banca, :count).by(1)
      end

      it "assigns a newly created banca as @banca" do
        post :create, {:banca => valid_attributes}, valid_session
        assigns(:banca).should be_a(Banca)
        assigns(:banca).should be_persisted
      end

      it "redirects to the created banca" do
        post :create, {:banca => valid_attributes}, valid_session
        response.should redirect_to(Banca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved banca as @banca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Banca.any_instance.stub(:save).and_return(false)
        post :create, {:banca => { "nome" => "invalid value" }}, valid_session
        assigns(:banca).should be_a_new(Banca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Banca.any_instance.stub(:save).and_return(false)
        post :create, {:banca => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested banca" do
        banca = Banca.create! valid_attributes
        # Assuming there are no other banche in the database, this
        # specifies that the Banca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Banca.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => banca.to_param, :banca => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested banca as @banca" do
        banca = Banca.create! valid_attributes
        put :update, {:id => banca.to_param, :banca => valid_attributes}, valid_session
        assigns(:banca).should eq(banca)
      end

      it "redirects to the banca" do
        banca = Banca.create! valid_attributes
        put :update, {:id => banca.to_param, :banca => valid_attributes}, valid_session
        response.should redirect_to(banca)
      end
    end

    describe "with invalid params" do
      it "assigns the banca as @banca" do
        banca = Banca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Banca.any_instance.stub(:save).and_return(false)
        put :update, {:id => banca.to_param, :banca => { "nome" => "invalid value" }}, valid_session
        assigns(:banca).should eq(banca)
      end

      it "re-renders the 'edit' template" do
        banca = Banca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Banca.any_instance.stub(:save).and_return(false)
        put :update, {:id => banca.to_param, :banca => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested banca" do
      banca = Banca.create! valid_attributes
      expect {
        delete :destroy, {:id => banca.to_param}, valid_session
      }.to change(Banca, :count).by(-1)
    end

    it "redirects to the banche list" do
      banca = Banca.create! valid_attributes
      delete :destroy, {:id => banca.to_param}, valid_session
      response.should redirect_to(banche_url)
    end
  end

end
