require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContributiController do

  # This should return the minimal set of attributes required to create a valid
  # Contributo. As you add validations to Contributo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codice" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContributiController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contributi as @contributi" do
      contributo = Contributo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contributi).should eq([contributo])
    end
  end

  describe "GET show" do
    it "assigns the requested contributo as @contributo" do
      contributo = Contributo.create! valid_attributes
      get :show, {:id => contributo.to_param}, valid_session
      assigns(:contributo).should eq(contributo)
    end
  end

  describe "GET new" do
    it "assigns a new contributo as @contributo" do
      get :new, {}, valid_session
      assigns(:contributo).should be_a_new(Contributo)
    end
  end

  describe "GET edit" do
    it "assigns the requested contributo as @contributo" do
      contributo = Contributo.create! valid_attributes
      get :edit, {:id => contributo.to_param}, valid_session
      assigns(:contributo).should eq(contributo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contributo" do
        expect {
          post :create, {:contributo => valid_attributes}, valid_session
        }.to change(Contributo, :count).by(1)
      end

      it "assigns a newly created contributo as @contributo" do
        post :create, {:contributo => valid_attributes}, valid_session
        assigns(:contributo).should be_a(Contributo)
        assigns(:contributo).should be_persisted
      end

      it "redirects to the created contributo" do
        post :create, {:contributo => valid_attributes}, valid_session
        response.should redirect_to(Contributo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contributo as @contributo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contributo.any_instance.stub(:save).and_return(false)
        post :create, {:contributo => { "codice" => "invalid value" }}, valid_session
        assigns(:contributo).should be_a_new(Contributo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contributo.any_instance.stub(:save).and_return(false)
        post :create, {:contributo => { "codice" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contributo" do
        contributo = Contributo.create! valid_attributes
        # Assuming there are no other contributi in the database, this
        # specifies that the Contributo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contributo.any_instance.should_receive(:update_attributes).with({ "codice" => "MyString" })
        put :update, {:id => contributo.to_param, :contributo => { "codice" => "MyString" }}, valid_session
      end

      it "assigns the requested contributo as @contributo" do
        contributo = Contributo.create! valid_attributes
        put :update, {:id => contributo.to_param, :contributo => valid_attributes}, valid_session
        assigns(:contributo).should eq(contributo)
      end

      it "redirects to the contributo" do
        contributo = Contributo.create! valid_attributes
        put :update, {:id => contributo.to_param, :contributo => valid_attributes}, valid_session
        response.should redirect_to(contributo)
      end
    end

    describe "with invalid params" do
      it "assigns the contributo as @contributo" do
        contributo = Contributo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contributo.any_instance.stub(:save).and_return(false)
        put :update, {:id => contributo.to_param, :contributo => { "codice" => "invalid value" }}, valid_session
        assigns(:contributo).should eq(contributo)
      end

      it "re-renders the 'edit' template" do
        contributo = Contributo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contributo.any_instance.stub(:save).and_return(false)
        put :update, {:id => contributo.to_param, :contributo => { "codice" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contributo" do
      contributo = Contributo.create! valid_attributes
      expect {
        delete :destroy, {:id => contributo.to_param}, valid_session
      }.to change(Contributo, :count).by(-1)
    end

    it "redirects to the contributi list" do
      contributo = Contributo.create! valid_attributes
      delete :destroy, {:id => contributo.to_param}, valid_session
      response.should redirect_to(contributi_url)
    end
  end

end
