require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FilialiController do

  # This should return the minimal set of attributes required to create a valid
  # Filiale. As you add validations to Filiale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FilialiController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all filiali as @filiali" do
      filiale = Filiale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:filiali).should eq([filiale])
    end
  end

  describe "GET show" do
    it "assigns the requested filiale as @filiale" do
      filiale = Filiale.create! valid_attributes
      get :show, {:id => filiale.to_param}, valid_session
      assigns(:filiale).should eq(filiale)
    end
  end

  describe "GET new" do
    it "assigns a new filiale as @filiale" do
      get :new, {}, valid_session
      assigns(:filiale).should be_a_new(Filiale)
    end
  end

  describe "GET edit" do
    it "assigns the requested filiale as @filiale" do
      filiale = Filiale.create! valid_attributes
      get :edit, {:id => filiale.to_param}, valid_session
      assigns(:filiale).should eq(filiale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Filiale" do
        expect {
          post :create, {:filiale => valid_attributes}, valid_session
        }.to change(Filiale, :count).by(1)
      end

      it "assigns a newly created filiale as @filiale" do
        post :create, {:filiale => valid_attributes}, valid_session
        assigns(:filiale).should be_a(Filiale)
        assigns(:filiale).should be_persisted
      end

      it "redirects to the created filiale" do
        post :create, {:filiale => valid_attributes}, valid_session
        response.should redirect_to(Filiale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved filiale as @filiale" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filiale.any_instance.stub(:save).and_return(false)
        post :create, {:filiale => { "nome" => "invalid value" }}, valid_session
        assigns(:filiale).should be_a_new(Filiale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Filiale.any_instance.stub(:save).and_return(false)
        post :create, {:filiale => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested filiale" do
        filiale = Filiale.create! valid_attributes
        # Assuming there are no other filiali in the database, this
        # specifies that the Filiale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Filiale.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => filiale.to_param, :filiale => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested filiale as @filiale" do
        filiale = Filiale.create! valid_attributes
        put :update, {:id => filiale.to_param, :filiale => valid_attributes}, valid_session
        assigns(:filiale).should eq(filiale)
      end

      it "redirects to the filiale" do
        filiale = Filiale.create! valid_attributes
        put :update, {:id => filiale.to_param, :filiale => valid_attributes}, valid_session
        response.should redirect_to(filiale)
      end
    end

    describe "with invalid params" do
      it "assigns the filiale as @filiale" do
        filiale = Filiale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filiale.any_instance.stub(:save).and_return(false)
        put :update, {:id => filiale.to_param, :filiale => { "nome" => "invalid value" }}, valid_session
        assigns(:filiale).should eq(filiale)
      end

      it "re-renders the 'edit' template" do
        filiale = Filiale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Filiale.any_instance.stub(:save).and_return(false)
        put :update, {:id => filiale.to_param, :filiale => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested filiale" do
      filiale = Filiale.create! valid_attributes
      expect {
        delete :destroy, {:id => filiale.to_param}, valid_session
      }.to change(Filiale, :count).by(-1)
    end

    it "redirects to the filiali list" do
      filiale = Filiale.create! valid_attributes
      delete :destroy, {:id => filiale.to_param}, valid_session
      response.should redirect_to(filiali_url)
    end
  end

end
