require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PosizioniController do

  # This should return the minimal set of attributes required to create a valid
  # Posizione. As you add validations to Posizione, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "numeroconto" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PosizioniController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all posizioni as @posizioni" do
      posizione = Posizione.create! valid_attributes
      get :index, {}, valid_session
      assigns(:posizioni).should eq([posizione])
    end
  end

  describe "GET show" do
    it "assigns the requested posizione as @posizione" do
      posizione = Posizione.create! valid_attributes
      get :show, {:id => posizione.to_param}, valid_session
      assigns(:posizione).should eq(posizione)
    end
  end

  describe "GET new" do
    it "assigns a new posizione as @posizione" do
      get :new, {}, valid_session
      assigns(:posizione).should be_a_new(Posizione)
    end
  end

  describe "GET edit" do
    it "assigns the requested posizione as @posizione" do
      posizione = Posizione.create! valid_attributes
      get :edit, {:id => posizione.to_param}, valid_session
      assigns(:posizione).should eq(posizione)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Posizione" do
        expect {
          post :create, {:posizione => valid_attributes}, valid_session
        }.to change(Posizione, :count).by(1)
      end

      it "assigns a newly created posizione as @posizione" do
        post :create, {:posizione => valid_attributes}, valid_session
        assigns(:posizione).should be_a(Posizione)
        assigns(:posizione).should be_persisted
      end

      it "redirects to the created posizione" do
        post :create, {:posizione => valid_attributes}, valid_session
        response.should redirect_to(Posizione.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved posizione as @posizione" do
        # Trigger the behavior that occurs when invalid params are submitted
        Posizione.any_instance.stub(:save).and_return(false)
        post :create, {:posizione => { "numeroconto" => "invalid value" }}, valid_session
        assigns(:posizione).should be_a_new(Posizione)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Posizione.any_instance.stub(:save).and_return(false)
        post :create, {:posizione => { "numeroconto" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested posizione" do
        posizione = Posizione.create! valid_attributes
        # Assuming there are no other posizioni in the database, this
        # specifies that the Posizione created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Posizione.any_instance.should_receive(:update_attributes).with({ "numeroconto" => "MyString" })
        put :update, {:id => posizione.to_param, :posizione => { "numeroconto" => "MyString" }}, valid_session
      end

      it "assigns the requested posizione as @posizione" do
        posizione = Posizione.create! valid_attributes
        put :update, {:id => posizione.to_param, :posizione => valid_attributes}, valid_session
        assigns(:posizione).should eq(posizione)
      end

      it "redirects to the posizione" do
        posizione = Posizione.create! valid_attributes
        put :update, {:id => posizione.to_param, :posizione => valid_attributes}, valid_session
        response.should redirect_to(posizione)
      end
    end

    describe "with invalid params" do
      it "assigns the posizione as @posizione" do
        posizione = Posizione.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Posizione.any_instance.stub(:save).and_return(false)
        put :update, {:id => posizione.to_param, :posizione => { "numeroconto" => "invalid value" }}, valid_session
        assigns(:posizione).should eq(posizione)
      end

      it "re-renders the 'edit' template" do
        posizione = Posizione.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Posizione.any_instance.stub(:save).and_return(false)
        put :update, {:id => posizione.to_param, :posizione => { "numeroconto" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested posizione" do
      posizione = Posizione.create! valid_attributes
      expect {
        delete :destroy, {:id => posizione.to_param}, valid_session
      }.to change(Posizione, :count).by(-1)
    end

    it "redirects to the posizioni list" do
      posizione = Posizione.create! valid_attributes
      delete :destroy, {:id => posizione.to_param}, valid_session
      response.should redirect_to(posizioni_url)
    end
  end

end
