require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RichiedentesController do

  # This should return the minimal set of attributes required to create a valid
  # Richiedente. As you add validations to Richiedente, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cana" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RichiedentesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all richiedentes as @richiedentes" do
      richiedente = Richiedente.create! valid_attributes
      get :index, {}, valid_session
      assigns(:richiedentes).should eq([richiedente])
    end
  end

  describe "GET show" do
    it "assigns the requested richiedente as @richiedente" do
      richiedente = Richiedente.create! valid_attributes
      get :show, {:id => richiedente.to_param}, valid_session
      assigns(:richiedente).should eq(richiedente)
    end
  end

  describe "GET new" do
    it "assigns a new richiedente as @richiedente" do
      get :new, {}, valid_session
      assigns(:richiedente).should be_a_new(Richiedente)
    end
  end

  describe "GET edit" do
    it "assigns the requested richiedente as @richiedente" do
      richiedente = Richiedente.create! valid_attributes
      get :edit, {:id => richiedente.to_param}, valid_session
      assigns(:richiedente).should eq(richiedente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Richiedente" do
        expect {
          post :create, {:richiedente => valid_attributes}, valid_session
        }.to change(Richiedente, :count).by(1)
      end

      it "assigns a newly created richiedente as @richiedente" do
        post :create, {:richiedente => valid_attributes}, valid_session
        assigns(:richiedente).should be_a(Richiedente)
        assigns(:richiedente).should be_persisted
      end

      it "redirects to the created richiedente" do
        post :create, {:richiedente => valid_attributes}, valid_session
        response.should redirect_to(Richiedente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved richiedente as @richiedente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Richiedente.any_instance.stub(:save).and_return(false)
        post :create, {:richiedente => { "cana" => "invalid value" }}, valid_session
        assigns(:richiedente).should be_a_new(Richiedente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Richiedente.any_instance.stub(:save).and_return(false)
        post :create, {:richiedente => { "cana" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested richiedente" do
        richiedente = Richiedente.create! valid_attributes
        # Assuming there are no other richiedentes in the database, this
        # specifies that the Richiedente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Richiedente.any_instance.should_receive(:update_attributes).with({ "cana" => "MyString" })
        put :update, {:id => richiedente.to_param, :richiedente => { "cana" => "MyString" }}, valid_session
      end

      it "assigns the requested richiedente as @richiedente" do
        richiedente = Richiedente.create! valid_attributes
        put :update, {:id => richiedente.to_param, :richiedente => valid_attributes}, valid_session
        assigns(:richiedente).should eq(richiedente)
      end

      it "redirects to the richiedente" do
        richiedente = Richiedente.create! valid_attributes
        put :update, {:id => richiedente.to_param, :richiedente => valid_attributes}, valid_session
        response.should redirect_to(richiedente)
      end
    end

    describe "with invalid params" do
      it "assigns the richiedente as @richiedente" do
        richiedente = Richiedente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Richiedente.any_instance.stub(:save).and_return(false)
        put :update, {:id => richiedente.to_param, :richiedente => { "cana" => "invalid value" }}, valid_session
        assigns(:richiedente).should eq(richiedente)
      end

      it "re-renders the 'edit' template" do
        richiedente = Richiedente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Richiedente.any_instance.stub(:save).and_return(false)
        put :update, {:id => richiedente.to_param, :richiedente => { "cana" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested richiedente" do
      richiedente = Richiedente.create! valid_attributes
      expect {
        delete :destroy, {:id => richiedente.to_param}, valid_session
      }.to change(Richiedente, :count).by(-1)
    end

    it "redirects to the richiedentes list" do
      richiedente = Richiedente.create! valid_attributes
      delete :destroy, {:id => richiedente.to_param}, valid_session
      response.should redirect_to(richiedentes_url)
    end
  end

end
