require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatiContributoController do

  # This should return the minimal set of attributes required to create a valid
  # StatoContributo. As you add validations to StatoContributo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatiContributoController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all stati_contributo as @stati_contributo" do
      stato_contributo = StatoContributo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:stati_contributo).should eq([stato_contributo])
    end
  end

  describe "GET show" do
    it "assigns the requested stato_contributo as @stato_contributo" do
      stato_contributo = StatoContributo.create! valid_attributes
      get :show, {:id => stato_contributo.to_param}, valid_session
      assigns(:stato_contributo).should eq(stato_contributo)
    end
  end

  describe "GET new" do
    it "assigns a new stato_contributo as @stato_contributo" do
      get :new, {}, valid_session
      assigns(:stato_contributo).should be_a_new(StatoContributo)
    end
  end

  describe "GET edit" do
    it "assigns the requested stato_contributo as @stato_contributo" do
      stato_contributo = StatoContributo.create! valid_attributes
      get :edit, {:id => stato_contributo.to_param}, valid_session
      assigns(:stato_contributo).should eq(stato_contributo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StatoContributo" do
        expect {
          post :create, {:stato_contributo => valid_attributes}, valid_session
        }.to change(StatoContributo, :count).by(1)
      end

      it "assigns a newly created stato_contributo as @stato_contributo" do
        post :create, {:stato_contributo => valid_attributes}, valid_session
        assigns(:stato_contributo).should be_a(StatoContributo)
        assigns(:stato_contributo).should be_persisted
      end

      it "redirects to the created stato_contributo" do
        post :create, {:stato_contributo => valid_attributes}, valid_session
        response.should redirect_to(StatoContributo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stato_contributo as @stato_contributo" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatoContributo.any_instance.stub(:save).and_return(false)
        post :create, {:stato_contributo => { "nome" => "invalid value" }}, valid_session
        assigns(:stato_contributo).should be_a_new(StatoContributo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatoContributo.any_instance.stub(:save).and_return(false)
        post :create, {:stato_contributo => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stato_contributo" do
        stato_contributo = StatoContributo.create! valid_attributes
        # Assuming there are no other stati_contributo in the database, this
        # specifies that the StatoContributo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StatoContributo.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => stato_contributo.to_param, :stato_contributo => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested stato_contributo as @stato_contributo" do
        stato_contributo = StatoContributo.create! valid_attributes
        put :update, {:id => stato_contributo.to_param, :stato_contributo => valid_attributes}, valid_session
        assigns(:stato_contributo).should eq(stato_contributo)
      end

      it "redirects to the stato_contributo" do
        stato_contributo = StatoContributo.create! valid_attributes
        put :update, {:id => stato_contributo.to_param, :stato_contributo => valid_attributes}, valid_session
        response.should redirect_to(stato_contributo)
      end
    end

    describe "with invalid params" do
      it "assigns the stato_contributo as @stato_contributo" do
        stato_contributo = StatoContributo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatoContributo.any_instance.stub(:save).and_return(false)
        put :update, {:id => stato_contributo.to_param, :stato_contributo => { "nome" => "invalid value" }}, valid_session
        assigns(:stato_contributo).should eq(stato_contributo)
      end

      it "re-renders the 'edit' template" do
        stato_contributo = StatoContributo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatoContributo.any_instance.stub(:save).and_return(false)
        put :update, {:id => stato_contributo.to_param, :stato_contributo => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stato_contributo" do
      stato_contributo = StatoContributo.create! valid_attributes
      expect {
        delete :destroy, {:id => stato_contributo.to_param}, valid_session
      }.to change(StatoContributo, :count).by(-1)
    end

    it "redirects to the stati_contributo list" do
      stato_contributo = StatoContributo.create! valid_attributes
      delete :destroy, {:id => stato_contributo.to_param}, valid_session
      response.should redirect_to(stati_contributo_url)
    end
  end

end
